### ISSUE TITLE
goesimage loses error codes from the processes that it runs

### ISSUE THREAD

**Issue by yurivict** [pigmonkey/goesimage#2]
For example, at some point ```convert``` began to fail and the ```goesimage``` still succeeds, and it doesn't print any message saying that the child process failed.

**Comment by pigmonkey** [comment]
Does the latest master work for you? I'm only wrapping `curl`, `feh`, and `convert`. Doing it for more common utils like `mkdir` and `file` seems like overkill, but I suppose we could wrap those as well.

I'm not returning the exit code of the failed process, as they may conflict with the exit codes returned by goesimage.

**Comment by yurivict** [comment]
Thanks for fixing this.
